version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    - mkdir -p /tmp/artifacts
    - cp -r build/* /tmp/artifacts  # Copy build artifacts to a temporary directory

artifacts:
  files: /tmp/artifacts/**/*
