version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files: '**/*'  # Include all files in the build output directory
  name: MyBuildArtifacts
  # discard-paths: no
  # build-directory: build
